packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.1.3
  '@types/mdx': 2.0.13
  '@types/react': 19.0.2
  '@types/react-dom': 19.0.2
  'next': 15.1.3
  'react': 19.0.0
  'react-dom': 19.0.0
  'restyle': 3.0.0
  'shiki': 1.26.0
  'ts-morph': 25.0.0
  'valibot': 1.0.0-beta.9
  'zod': 3.24.1
