packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.2.4
  '@types/mdx': 2.0.13
  '@types/react': 19.0.12
  '@types/react-dom': 19.0.4
  'next': 15.2.4
  'react': 19.0.0
  'react-dom': 19.0.0
  'restyle': 3.1.3
  'ts-morph': 25.0.1
  'valibot': 1.0.0
  'zod': 3.24.2
