packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.1.4
  '@types/mdx': 2.0.13
  '@types/react': 19.0.7
  '@types/react-dom': 19.0.3
  'next': 15.1.4
  'react': 19.0.0
  'react-dom': 19.0.0
  'restyle': 3.1.1
  'shiki': 1.27.2
  'ts-morph': 25.0.0
  'valibot': 1.0.0-beta.12
  'zod': 3.24.1
