name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: 'Turn on verbose debug output'
        type: boolean
        default: false

concurrency: release-main

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  NODE_ENV: production
  RENOUN_DEBUG: ${{ inputs.debug }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: pnpm build --filter=!@examples/*

      - name: Publish to npm
        id: publish
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Fast-forward release branch
        if: steps.publish.outputs.published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          MAIN_SHA=$(git rev-parse origin/main)
          git push --force-with-lease \
            "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" \
            "$MAIN_SHA:refs/heads/release"

      - name: Notify Discord
        if: steps.publish.outputs.published == 'true'
        env:
          PUBLISHED_PACKAGES: ${{ steps.publish.outputs.publishedPackages }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          OWNER_REPO="souporserious/renoun"

          # Validate JSON structure first
          if ! jq empty <<< "$PUBLISHED_PACKAGES" 2>/dev/null; then
            echo "Invalid JSON in PUBLISHED_PACKAGES"
            exit 1
          fi

          # Use here-string to avoid echo interpretation
          lines=$(jq -r --arg repo "$OWNER_REPO" '
            try ( .[] | "\(.name)@\(.version) — https://github.com/\($repo)/releases/tag/\(.name)@\(.version)" )
            catch empty
          ' <<< "$PUBLISHED_PACKAGES")

          if [ -z "$lines" ]; then
            echo "No packages parsed; skipping Discord notification."
            exit 0
          fi

          # Limit output safely
          trimmed=$(printf "%s\n" "$lines" | head -n 30 | head -c 1800)

          # Send to Discord using jq for proper JSON encoding
          jq -n --arg msg "🚀 New packages released:\n$trimmed" '{ content: $msg }' \
          | curl -sS -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"
